import { useState } from 'react';
import Head from 'next/head';

export default function MediaReportsAdmin() {
  const [token, setToken] = useState(''); const [reports, setReports] = useState<any[]>([]); const [status, setStatus] = useState('Enter the admin API token.');
  const load = async () => { const response = await fetch('/api/admin/media-reports', { headers: { Authorization: `Bearer ${token}` } }); const data = await response.json(); if (!response.ok) return setStatus(data.message || 'Could not load reports'); setReports(data); setStatus(`Loaded ${data.length} media reports.`); };
  const review = async (id: string, nextStatus: string) => { const response = await fetch('/api/admin/media-reports', { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ id, status: nextStatus }) }); if (response.ok) await load(); };
  return <><Head><title>Media Reports | MASFAH Admin</title></Head><main className="mx-auto max-w-5xl p-6"><h1 className="text-3xl font-black">Media moderation</h1><p className="mt-2 text-gray-600">Review reports for unauthorized, unsafe, or inappropriate business content.</p><div className="mt-6 flex gap-2"><input type="password" value={token} onChange={(event) => setToken(event.target.value)} placeholder="Admin API token" className="flex-1 rounded-lg border p-3" /><button onClick={load} className="rounded-lg bg-black px-4 py-3 font-bold text-white">Load</button></div><p className="mt-4 rounded-lg bg-blue-50 p-3 text-blue-800">{status}</p><div className="mt-6 space-y-3">{reports.map((report) => <article key={report.id} className="rounded-xl border p-4"><div className="flex justify-between gap-4"><div><b>{report.reason}</b><p className="text-sm text-gray-600">{report.business?.nameEn} · {report.status}</p></div><div className="flex gap-2"><button onClick={() => review(report.id, 'DISMISSED')} className="rounded border px-3 py-2">Dismiss</button><button onClick={() => review(report.id, 'REMOVED')} className="rounded bg-red-700 px-3 py-2 text-white">Remove</button></div></div><p className="mt-2 text-sm">{report.details}</p></article>)}{!reports.length && <p className="text-gray-500">No reports loaded.</p>}</div></main></>;
}
